
export type Mod = {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  difficulty: 'Easy' | 'Normal' | 'Hard' | 'Insane';
  songs: number;
  bonusSongs?: number;
  buildType?: string;
  gameUrl?: string;
};

export const mods: Mod[] = [
  {
    id: 'vs-whitty',
    title: 'V.S. Whitty',
    description: 'Face off against the short-fused rock star, Whitty.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/7/71/WhittyWeek.jpg/revision/latest/scale-to-width-down/536?cb=20210217011836',
    difficulty: 'Hard',
    songs: 3,
    bonusSongs: 1,
    gameUrl: 'https://fnf.run3.io/whitty/5/',
  },
  {
    id: 'vs-whitty-definitive',
    title: 'V.S. Whitty - Definitive Edition',
    description: 'The iconic mod\'s definitive edition.',
    imageUrl: 'https://images.gamebanana.com/img/ss/mods/530-90_61f9bf6a4abea.jpg',
    difficulty: 'Hard',
    songs: 10,
    bonusSongs: 7,
    gameUrl: 'https://fnf.kdata1.com/whitty-definitive-edition/1.5/',
  },
  {
    id: 'the-tricky-mod',
    title: 'The Tricky Mod',
    description: 'Battle the chaotic clown, Tricky.',
    imageUrl: 'https://images.gamebanana.com/img/ss/mods/60b7d8741ac99.jpg',
    difficulty: 'Insane',
    songs: 3,
    bonusSongs: 1,
    gameUrl: 'https://fnf.run3.io/tricky2/4/',
  },
  {
    id: 'vs-hex',
    title: 'V.S. Hex',
    description: 'A match against a robot basketballer.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/d/da/Hexupdatebanner.png/revision/latest/scale-to-width-down/1000?cb=20220104085525',
    difficulty: 'Normal',
    songs: 5,
    gameUrl: 'https://fnf.kdata1.com/hex-weekend/2/',
  },
  {
    id: 'hazy-river',
    title: 'Hazy River',
    description: 'A Garcello and Annie mod remaster.',
    imageUrl: 'https://images.gamebanana.com/img/ss/mods/626efdcd46c73.jpg',
    difficulty: 'Hard',
    songs: 16,
    buildType: 'Remaster',
    gameUrl: 'https://fnf.kdata1.com/hazy-river-vs-garcello-annie/1/',
  },
  {
    id: 'mid-fight-masses',
    title: 'Mid-Fight Masses',
    description: 'A full week mod with Sarvente.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/a/a7/Midfight_Masses_Update_Banner.jpg/revision/latest/scale-to-width-down/536?cb=20210327100359',
    difficulty: 'Hard',
    songs: 4,
    gameUrl: 'https://fnf.run3.io/midfight/2/',
  },
  {
    id: 'vs-selever',
    title: 'V.S. Selever',
    description: "Face off against Sarvente's non-canon son.",
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/6/6f/VsSeleverThumbnail.png/revision/latest/scale-to-width-down/1000?cb=20210928225526',
    difficulty: 'Hard',
    songs: 3,
    gameUrl: 'https://fnf.run3.io/selever-full-week/1/',
  },
  {
    id: 'vs-tabi',
    title: 'V.S. Tabi',
    description: 'Face Girlfriend\'s vengeful ex.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/9/9b/530-90_60a2714b4e6a0.jpg/revision/latest?cb=20210601073903',
    difficulty: 'Hard',
    songs: 3,
    gameUrl: 'https://fnf.run3.io/tabi/5/',
  },
  {
    id: 'tabi-revival',
    title: 'Tabi Revival',
    description: 'A revival of the classic Tabi mod.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/a/a0/62549a860885b.jpg/revision/latest/scale-to-width-down/1000?cb=20220412051715',
    difficulty: 'Hard',
    songs: 3,
    gameUrl: 'https://fnf.kdata1.com/2025/tabi-revival/1/',
  },
  {
    id: 'starlight-mayhem',
    title: 'Starlight Mayhem Rebooted',
    description: 'Rock out against CJ and his band.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/c/cf/StarlightMayhemRebootedBanner.jpeg/revision/latest/scale-to-width-down/1000?cb=20211222071757',
    difficulty: 'Normal',
    songs: 3,
    gameUrl: 'https://fnf.kdata1.com/starlight-mayhem-rebooted/1.5/?D434d3',
  },
  {
    id: 'vs-kapi',
    title: 'V.S. Kapi: Arcade Showdown',
    description: 'An arcade showdown with a cat-boy.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/a/ac/Banner_arcade_showdown_new.png/revision/latest/scale-to-width-down/536?cb=20220220040823',
    difficulty: 'Normal',
    songs: 4,
    gameUrl: 'https://fnf.kdata1.com/kapi-arcade-showdown/2/',
  },
  {
    id: 'indie-cross',
    title: 'Indie Cross',
    description: 'An epic indie game crossover.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/e/ed/Indie_Cross_New_Banner.png/revision/latest?cb=20220415010428',
    difficulty: 'Insane',
    songs: 22,
    gameUrl: 'https://gamaverse.com/c/f/g/fnf-indie-cross-vs-cuphead-sans-bendy/index.html',
  },
  {
    id: 'doki-doki-takeover',
    title: 'Doki Doki Takeover Plus',
    description: 'The DDLC literature club takes over.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/4/44/DDTO%2BBanner.jpg/revision/latest/scale-to-width-down/1000?cb=20230318160553',
    difficulty: 'Normal',
    songs: 8,
    gameUrl: 'https://kdata1.com/5000/2025/doki-doki-takeover-ddlc/',
  },
  {
    id: 'vs-impostor',
    title: 'V.S. Impostor',
    description: 'Among Us comes to FNF!',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/4/48/63aa9e7414efa.jpg/revision/latest/scale-to-width-down/536?cb=20230104055956',
    difficulty: 'Hard',
    songs: 7,
    gameUrl: 'https://fnf.kdata1.com/impostor-v4/1.5/',
  },
  {
    id: 'vs-impostor-2025',
    title: 'V.S. Impostor (2025)',
    description: 'The 2025 edition of the Among Us FNF mod.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/1/1c/VsImpostor2025Banner.jpg/revision/latest/scale-to-width-down/536?cb=20250402125604',
    difficulty: 'Hard',
    songs: 5,
    gameUrl: 'https://fnf.kdata1.com/2025/impostor-2025/15/',
  },
  {
    id: 'holofunk',
    title: 'HoloFunk',
    description: 'Battle Hololive EN V-Tubers.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/f/f0/HoloNight_Funkin_Banner.jpg/revision/latest?cb=20210617013629',
    difficulty: 'Normal',
    songs: 20,
    gameUrl: 'https://fnf.run3.io/holofunk/2.2/',
  },
  {
    id: 'vs-rewrite',
    title: 'V.S. Rewrite',
    description: 'Face off against the powerful Rewrite.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/3/38/RewriteBanner2.jpeg/revision/latest?cb=20230125055951',
    difficulty: 'Insane',
    songs: 4,
    gameUrl: 'https://fnf.kdata1.com/rewrite-sonic-exe/1.2/',
  },
  {
    id: 'vs-mario-ultra-rebooted',
    title: 'V.S. Mario Ultra Rebooted',
    description: 'Take on Mario in this FNF mod.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/6/68/MarioBanner.jpeg/revision/latest?cb=20220329232402',
    difficulty: 'Hard',
    songs: 4,
    gameUrl: 'https://fnf.kdata1.com/mario-ultra-rebooted/1/',
  },
  {
    id: 'dave-and-bambi',
    title: 'Dave & Bambi',
    description: 'A unique mod with a 3D art style.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/4/40/DaveandBambi3.0banner.jpg/revision/latest?cb=20221001163538',
    difficulty: 'Insane',
    songs: 32,
    gameUrl: 'https://fnf.kdata1.com/dave-bambi/32/',
  },
  {
    id: 'dave-and-bambi-golden-apple',
    title: 'Dave & Bambi: Golden Apple',
    description: 'A fan-made expansion to the Dave & Bambi mod.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/7/76/GappleBanner2.jpg/revision/latest/scale-to-width-down/1000?cb=20230214014136',
    difficulty: 'Insane',
    songs: 20,
    gameUrl: 'https://fnf.kdata1.com/dave-bambi-golden-apple/1/',
  },
  {
    id: 'entity',
    title: 'Entity',
    description: 'A huge mod featuring AGOTI.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/4/4a/Fnfentityful.jpg/revision/latest?cb=20211204000308',
    difficulty: 'Hard',
    songs: 4,
  },
  {
    id: 'vs-shaggy',
    title: 'V.S. Shaggy',
    description: 'Battle the legendary Shaggy Rogers.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/3/3e/Shaggyupdate.png/revision/latest/scale-to-width-down/536?cb=20220118103721',
    difficulty: 'Insane',
    songs: 7,
    gameUrl: 'https://fnf.run3.io/shaggy-pe/1.25/',
  },
  {
    id: 'shaggy-x-matt',
    title: 'Shaggy x Matt',
    description: 'The ultimate showdown of power.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/d/d1/SxMGameJoltBanner2.png/revision/latest?cb=20230413220256',
    difficulty: 'Insane',
    songs: 9,
    gameUrl: 'https://fnf.run3.io/shaggy-matt/1.5/',
  },
  {
    id: 'vs-matt',
    title: 'V.S. Matt',
    description: 'Challenge Matt from Wii Sports.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/6/69/606b35d5e501e.jpg/revision/latest/scale-to-width-down/536?cb=20210406052627',
    difficulty: 'Insane',
    songs: 5,
    gameUrl: 'https://run3.io/popgame/fnf/mattwii-2/?ddd',
  },
  {
    id: 'vs-matt-wiik3',
    title: 'V.S. Matt - Wiik 3 (Fanmade)',
    description: 'A fan-made continuation of the Matt saga.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/5/53/WiiK3%2BGBBanner.jpg/revision/latest/scale-to-width-down/536?cb=20230426205750',
    difficulty: 'Insane',
    songs: 9,
    gameUrl: 'https://fnf.run3.io/matt-3-fanmade/3.1/',
  },
  {
    id: 'vs-matt-wiik4',
    title: 'V.S. Matt - Wiik 4 (Fanmade)',
    description: 'The fan-made Wiik 4 with more intense challenges.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/1/18/Wiik4RemasterGBBanner.jpg/revision/latest/scale-to-width-down/536?cb=20230505174705',
    difficulty: 'Insane',
    songs: 13,
    bonusSongs: 32,
    gameUrl: 'https://fnf.run3.io/matt-wiik-4-fanmade/1/',
  },
  {
    id: 'vs-matt-wiik4-rozebud',
    title: 'V.S. Matt - Wiik 4 (Rozebud)',
    description: 'Rozebud\'s take on the Wiik 4 challenge.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/1/18/WF4GBBanner.jpg/revision/latest/scale-to-width-down/536?cb=20230502145931',
    difficulty: 'Insane',
    songs: 6,
    bonusSongs: 1,
    gameUrl: 'https://fnf.kdata1.com/wii-funkin-wiik-4-fanmade/1/',
  },
  {
    id: 'matt-voiid-chronicles',
    title: 'Matt: Voiid Chronicles',
    description: 'An expansive Matt mod with new mechanics.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/7/74/VoiidNewBanner.jpg/revision/latest/scale-to-width-down/536?cb=20230812032443',
    difficulty: 'Insane',
    songs: 43,
    bonusSongs: 38,
    gameUrl: 'https://fnf.kdata1.com/matt-voiid-sides/1/',
  },
  {
    id: 'vs-matt-wiik100',
    title: 'V.S. Matt - Wiik 100',
    description: 'The ultimate test of skill against Matt.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/3/31/MattWiik100GameBanana.jpg/revision/latest/scale-to-width-down/536?cb=20210929191310',
    difficulty: 'Insane',
    songs: 3,
    gameUrl: 'https://fnf.kdata1.com/matt-wiik-1000/1/',
  },
  {
    id: 'friday-night-fever',
    title: 'Friday Night Fever: Frenzy',
    description: 'A massive full-game overhaul mod.',
    imageUrl: 'https://images.gamebanana.com/img/ss/mods/63d738694de37.jpg',
    difficulty: 'Normal',
    songs: 20,
    gameUrl: 'https://fnf.kdata1.com/fever/1/',
  },
  {
    id: 'vs-rainbow-friends',
    title: 'V.S. Rainbow Friends',
    description: 'Face off against the colorful characters from Rainbow Friends.',
    imageUrl: 'https://static.wikia.nocookie.net/9e029e1b-c4e9-4920-bb23-cbde1dd222c6/scale-to-width/755',
    difficulty: 'Normal',
    songs: 1,
    gameUrl: 'https://fnf.kdata1.com/rainbow-friends/1',
  },
  {
    id: 'vs-blue',
    title: 'V.S. Blue',
    description: 'Take on Blue from the popular Roblox game Rainbow Friends.',
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/7/75/633763a85217d.jpg/revision/latest/scale-to-width-down/1000?cb=20221123150645',
    difficulty: 'Normal',
    songs: 1,
    bonusSongs: 1,
    gameUrl: 'https://fnf.kdata1.com/roblox-rainbow-friends-vs-blue/1/',
  },
  {
    id: 'sprunkin',
    title: 'Sprunkin\'!',
    description: "Only for the Brainrotted",
    imageUrl: 'https://static.wikia.nocookie.net/fridaynightfunking/images/1/16/Sprunkinthumnail.jpg/revision/latest/scale-to-width-down/1000?cb=20241015225512',
    difficulty: 'Normal',
    songs: 3,
    gameUrl: 'https://fnf.kdata1.com/2024/sprunki-sprunkin/1/',
  }
];

    
